title: 技术文章
subtitle: 分享我的技术文章和学习笔记

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: articles

categories:
  - name: 最新文章
    icon: fas fa-pen
    sites:
      - name: 用篡改猴脚本刷Bing搜索积分
        icon: fas fa-search
        description: 使用篡改猴（Tampermonkey）脚本来自动化获取Bing搜索积分，轻松刷满每日积分上限
        url: "https://z-z-h.xyz/sop/gemini-bing-points-script.html"
      - name: 从角色扮演到剧情聊天，翻开AI的另一面
        icon: fas fa-robot
        description: 探索AI角色扮演和剧情聊天的可能性，体验AI交互的新维度
        url: "https://z-z-h.xyz/sop/ai-role-play.html"
      - name: 如何使用 Cherry Studio
        icon: fas fa-tools
        description: Cherry Studio使用指南和技巧分享
        url: "https://z-z-h.xyz/sop/how-to-use-cherry-studio.html" 