title: 我的项目
subtitle: 这里展示了我的一些个人项目和开源贡献

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: projects

categories:
  - name: 个人项目
    icon: fas fa-code
    sites:
      - name: 五子棋AI
        icon: fas fa-chess-board
        description: 基于C++的五子棋AI对战系统，支持神经网络训练
        url: https://github.com/handsomezhuzhu/gobang
      - name: 英语单词本
        icon: fas fa-book
        description: 网页版生词本，记录单词和翻译
        url: https://github.com/handsomezhuzhu/English-words 